export const STATUS_CODE: any = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const ROLE: any = {
  ADMIN: 1,
  MEMBER: 2,
  CONTESTANT: 3,
};
